#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libxklavier
Version  : 5.4
Release  : 9
URL      : https://github.com/freedesktop/libxklavier/archive/libxklavier-5.4.tar.gz
Source0  : https://github.com/freedesktop/libxklavier/archive/libxklavier-5.4.tar.gz
Summary  : libxklavier library
Group    : Development/Tools
License  : LGPL-2.0
Requires: libxklavier-data = %{version}-%{release}
Requires: libxklavier-lib = %{version}-%{release}
Requires: libxklavier-license = %{version}-%{release}
BuildRequires : docbook-xml
BuildRequires : glib-dev
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : intltool
BuildRequires : libxkbfile-dev
BuildRequires : libxml2-dev
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(iso-codes)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xi)
BuildRequires : pkgconfig(xorg-server)
BuildRequires : vala
BuildRequires : xkbcomp-bin

%description
libxklavier - utility library to make XKB stuff easier
Sergey V. Udaltsov

%package data
Summary: data components for the libxklavier package.
Group: Data

%description data
data components for the libxklavier package.


%package dev
Summary: dev components for the libxklavier package.
Group: Development
Requires: libxklavier-lib = %{version}-%{release}
Requires: libxklavier-data = %{version}-%{release}
Provides: libxklavier-devel = %{version}-%{release}
Requires: libxklavier = %{version}-%{release}

%description dev
dev components for the libxklavier package.


%package lib
Summary: lib components for the libxklavier package.
Group: Libraries
Requires: libxklavier-data = %{version}-%{release}
Requires: libxklavier-license = %{version}-%{release}

%description lib
lib components for the libxklavier package.


%package license
Summary: license components for the libxklavier package.
Group: Default

%description license
license components for the libxklavier package.


%prep
%setup -q -n libxklavier-libxklavier-5.4
cd %{_builddir}/libxklavier-libxklavier-5.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604609933
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1604609933
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libxklavier
cp %{_builddir}/libxklavier-libxklavier-5.4/COPYING.LIB %{buildroot}/usr/share/package-licenses/libxklavier/b256632dcce76559734ff0a23330d2898b7d3a3b
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Xkl-1.0.typelib
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/libxklavier/xkl-enum-types.h
/usr/include/libxklavier/xkl_config_item.h
/usr/include/libxklavier/xkl_config_rec.h
/usr/include/libxklavier/xkl_config_registry.h
/usr/include/libxklavier/xkl_engine.h
/usr/include/libxklavier/xkl_engine_marshal.h
/usr/include/libxklavier/xklavier.h
/usr/lib64/libxklavier.so
/usr/lib64/pkgconfig/libxklavier.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libxklavier.so.16
/usr/lib64/libxklavier.so.16.4.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libxklavier/b256632dcce76559734ff0a23330d2898b7d3a3b
