#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libxklavier
Version  : 5.4
Release  : 3
URL      : http://pkgs.fedoraproject.org/repo/pkgs/libxklavier/libxklavier-5.4.tar.bz2/13af74dcb6011ecedf1e3ed122bd31fa/libxklavier-5.4.tar.bz2
Source0  : http://pkgs.fedoraproject.org/repo/pkgs/libxklavier/libxklavier-5.4.tar.bz2/13af74dcb6011ecedf1e3ed122bd31fa/libxklavier-5.4.tar.bz2
Summary  : Libraries, includes, etc to develop libxklavier applications
Group    : Development/Tools
License  : LGPL-2.0
Requires: libxklavier-lib
Requires: libxklavier-doc
Requires: libxklavier-data
BuildRequires : docbook-xml
BuildRequires : glib-dev
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxkbfile-dev
BuildRequires : libxml2-dev
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(iso-codes)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xi)
BuildRequires : pkgconfig(xorg-server)
BuildRequires : xkbcomp-bin

%description
This library allows you simplify XKB-related development.

%package data
Summary: data components for the libxklavier package.
Group: Data

%description data
data components for the libxklavier package.


%package dev
Summary: dev components for the libxklavier package.
Group: Development
Requires: libxklavier-lib
Requires: libxklavier-data
Provides: libxklavier-devel

%description dev
dev components for the libxklavier package.


%package doc
Summary: doc components for the libxklavier package.
Group: Documentation

%description doc
doc components for the libxklavier package.


%package lib
Summary: lib components for the libxklavier package.
Group: Libraries
Requires: libxklavier-data

%description lib
lib components for the libxklavier package.


%prep
%setup -q -n libxklavier-5.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1500495081
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1500495081
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Xkl-1.0.typelib
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/libxklavier/xkl-enum-types.h
/usr/include/libxklavier/xkl_config_item.h
/usr/include/libxklavier/xkl_config_rec.h
/usr/include/libxklavier/xkl_config_registry.h
/usr/include/libxklavier/xkl_engine.h
/usr/include/libxklavier/xkl_engine_marshal.h
/usr/include/libxklavier/xklavier.h
/usr/lib64/libxklavier.so
/usr/lib64/pkgconfig/libxklavier.pc

%files doc
%defattr(-,root,root,-)
/usr/share/gtk-doc/html/libxklavier/XklConfigItem.html
/usr/share/gtk-doc/html/libxklavier/XklConfigRec.html
/usr/share/gtk-doc/html/libxklavier/XklConfigRegistry.html
/usr/share/gtk-doc/html/libxklavier/ch01.html
/usr/share/gtk-doc/html/libxklavier/ch02.html
/usr/share/gtk-doc/html/libxklavier/home.png
/usr/share/gtk-doc/html/libxklavier/index.html
/usr/share/gtk-doc/html/libxklavier/index.sgml
/usr/share/gtk-doc/html/libxklavier/left.png
/usr/share/gtk-doc/html/libxklavier/libxklavier-xkl-engine.html
/usr/share/gtk-doc/html/libxklavier/libxklavier-xklavier.html
/usr/share/gtk-doc/html/libxklavier/libxklavier.devhelp2
/usr/share/gtk-doc/html/libxklavier/right.png
/usr/share/gtk-doc/html/libxklavier/style.css
/usr/share/gtk-doc/html/libxklavier/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libxklavier.so.16
/usr/lib64/libxklavier.so.16.4.0
